name: Docker Build and Publish

on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
      - develop

env:
  IMAGE_NAME: webmin

jobs:
  # Job para preparar metadata y tags
  prepare:
    runs-on: ubuntu-latest
    outputs:
      is_master: ${{ github.ref == 'refs/heads/master' }}
      sha: ${{ github.sha }}
      ref_name: ${{ github.ref_name }}
    steps:
      - name: Set outputs
        id: meta
        run: echo "Metadata prepared"

  # Job para construir y publicar la imagen
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ needs.prepare.outputs.is_master }}
            type=raw,value=${{ needs.prepare.outputs.sha }}
            type=raw,value=${{ needs.prepare.outputs.ref_name }}-${{ needs.prepare.outputs.sha }},enable=${{ !needs.prepare.outputs.is_master }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Job para pruebas en AMD64
  test-amd64:
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: github.event_name != 'pull_request'
    steps:
      - name: Test AMD64 container
        run: |
          TAG=${{ needs.prepare.outputs.sha }}
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG}
          docker run -d --name test-webmin-amd64 -p 10000:10000 ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG}
          sleep 30
          docker ps
          docker logs test-webmin-amd64
          curl -k --retry 5 --retry-delay 10 https://localhost:10000/ || exit 1

  # Job para pruebas en ARM64 usando emulación
  test-arm64:
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: github.event_name != 'pull_request'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Test ARM64 container
        run: |
          TAG=${{ needs.prepare.outputs.sha }}
          docker pull --platform linux/arm64 ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG}
          docker run --platform linux/arm64 -d --name test-webmin-arm64 -p 10001:10000 ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG}
          sleep 30
          docker ps
          docker logs test-webmin-arm64
          curl -k --retry 5 --retry-delay 10 https://localhost:10001/ || exit 1

  # Job final que espera que todas las pruebas pasen
  success:
    needs: [test-amd64, test-arm64]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Success
        run: echo "All tests passed successfully!"